import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  const recipes = data.recipes;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>{recipes[0].title}</h1>
    </div>
  )
}

// this runs when we built and deploy the app
export function getStaticProps() {
  return {
    props: {
      data: {
        recipes: [{title: "mongo lassi"}]
      }
    }
  }
}